# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Duhoe Kim
title: developer
email: doo6310@gmail.com
website: https://doo6310.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  doo6310
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <mark>c++</mark>, <mark>c#</mark>, <mark>javascript</mark>, <mark>python</mark>, <mark>java</mark>, <mark>nodejs</mark>, <mark>vue</mark> 등 다양한 언어 및 플랫폼을 취급하고 있으며, 특정 언어가 주력이 아닌 목적에 필요한 언어를 언제든지 가져다 사용할 수 있는 것을 목표로 하고 있습니다.
  
  목표한 방향으로 프로그램이 돌아가는것을 체크 하기 위해 디버깅 환경 구성하는 것을 중요하게 생각하고 있으며, 예외 상황이 생겼을때 재현하는 환경 등을 주로 만들어서 사용한 경험이 다수 있습니다.
  
  빌드 자동화에도 관심을 갖고 <mark>docker</mark>, <mark>jenkins</mark>를  지속적으로 관찰 중 입니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nuricon
        link: nuricon.co.kr
        # link_text: http://www.nuricon.co.kr/
        sub_title: Developer
        caption: November 2020 - Present
        quote: >
          뛰어난 기술력을 바탕으로 IP Wall Controller 시장의 점유율 1위를 고수하며, AI Vision 분야의 혁신적인 주차 시스템을 제공
        description: | # this will include new lines to allow paragraphs
            IP Wall은 모든 매체의 영상을 별도의 장비 없이 Network나, 영상케이블로 입력받아 다양한 형태의 Display에 실시간으로 표출 가능합니다.
            
            Smart Parking은 AI 기술을 이용해 주차장에 설치된 CCTV 영상을 분석하여 운전자에게 실시간으로 정보를 제공함으로써 주차장 이용 가능 여부 및 정확한 주차 위치정보를 제공하는 시스템입니다.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sejong University Graduate School
        caption: 2015 - 2019
        sub_title: Computer Engineering
        quote: >
          세종대학교에서 석박사 통합과정으로 학위를 받았으며, 대학원에서 병역특례인 전문연구요원으로 복무했습니다.
        description: | 
          대학원에서는 주로 ADD와 사이버전에 관한 기초 연구를 진행했습니다. 이외에도 하둡 에코시스템을 사용하여 보안로그를 수집 및 분석, 데이터 마이닝을 통한 사용자 행위 패턴 추출 및 예측, 로그 분석을 이용한 공격 탐지 어플리케이션 개발 등 다양한 방면으로 연구를 진행했습니다.
          
          특허로는 라이브 포렌식 기반 공격 탐지 장치 및 방법, 로그 분석을 이용한 공격 탐지 장치 및 방법 두 개를 가지고 있고, 로그 분석을 이용한 공격 탐지 장치 및 방법은 기술이전을 진행하였습니다.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
