# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Duhoe Kim
title: developer
email: doo6310@gmail.com
website: https://doo6310.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  doo6310
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <mark>c++</mark>, <mark>c#</mark>, <mark>javascript</mark>, <mark>python</mark>, <mark>java</mark>, <mark>nodejs</mark>, <mark>vue</mark> 등 다양한 언어 및 플랫폼을 취급하고 있으며, 특정 언어가 주력이 아닌 목적에 필요한 언어를 언제든지 가져다 사용할 수 있는 것을 목표로 하고 있습니다.
  
  목표한 방향으로 프로그램이 돌아가는것을 체크 하기 위해 디버깅 환경 구성하는 것을 중요하게 생각하고 있으며, 예외 상황이 생겼을때 재현하는 환경 등을 주로 만들어서 사용한 경험이 다수 있습니다.
  
  빌드 자동화에도 관심을 갖고 <mark>docker</mark>, <mark>jenkins</mark>를  지속적으로 관찰 중 입니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: project
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        # - title:  sproogen/modern-resume-theme
        #   icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 신분증 인식 프로그램
        caption: 2020.2 - 2020.4
        quote: >
          신분증을 인식하여 신분증 내에 있는 텍스트들을 추출하여 OCR로 인식하는 프로그램
        description: | 
          신사업팀으로 입사 후 맨 처음 제가 맡은 작업은 AI모델들의 성능을 조사하는 것이었습니다.
          주민등록증의 텍스트를 인식하기위해 Detection model들을 조사하여 어떤 모델이 적합한지 테스트 진행 하였습니다.(YOLO, EAST 등)
          
          학습 데이터가 적어서 주민등록증이 틀어지거나 크기가 크면 인식률이 떨어지게 되어 새로운 방안을 찾아야 했습니다.
          다수의 주민등록증을 구하기에 어려움이 있어 Python으로 generator를 개발하여 틀어진 각도나, 사이즈, 위치 등을 랜덤하게 하여 신분증 데이터를 생성하는 작업을 진행하였습니다.
          
          generator로 생성한 데이터를 학습시키고 안드로이드에서 사용가능하게 tflite로 변환하여 카메라를 사용한 안드로이드 어플리케이션으로 제작하였습니다.
          
      - layout: left
        title: viewflex에서 사용하는 영상표출 플레이어 구현
        caption: 2020.6 - 2020.9
        quote: >
          장보고 잠수함 훈련장에 사용할 multicast 영상을 받아서 표출하는 플레이어 구현
        description: | 
          병역특례로 훈련소를 다녀오니 조직도가 변경되어 있어 다른팀에서 일해볼 기회가 생겼습니다.
          멀티캐스트 36개의 영상을 받아서 표출하는 플레이어를 C#으로 구현하였습니다. 다른 회사와 헤더를 규약하고 데이터가 들어오면 영상인지 소리인지 구분하여 영상만 표출하는 부분을 구현하고, 소리는 별도로 버튼을 이용하여 On/Off 가능하게 구현하였습니다.
          
          이 당시에 영상이 2/3만 표출되는 현상이 생겼었습니다. 원인을 찾기위해 wireshark로 Raw 데이터를 열어서 정상적인 데이터가 들어오는지 확인하고, RTP 데이터를 분석해봤지만 이상이 없어서 문제점을 찾는데 시간이 오래 걸렸습니다.
          
          문제가 버퍼 사이즈 때문이었는데, c#에서 사용하는 기본 버퍼 사이즈가 8192바이트로 되어 있기 때문에 한 프레임이 버퍼 안에 들어오지 못한 데이터가 생기면 소실되어버려 영상이 잘려서 재생이 된 것입니다. 단 한 줄 수정해주니 정상적으로 영상이 표출되는 것을 보고 좋았지만 한편으로는 언어의 이해도가 중요하다는 걸 깨달았습니다.
          
      - layout: left
        title: viewflex 리팩토링
        caption: 2020.10 - 2021.8
        quote: >
          구조적 한계 극복을 위한 코드 리팩토링
        description: | 
          기존의 돌아가는 프로그램을 유지보수 하면서, 유지보수 외 시간에는 현재의 프로그램을 재설계하여 구현하는 작업을 진행했습니다. 기능은 기존버젼 그대로 가져오되, 구조는 확장성을 더 고려하여 추가적인 기능이나 요구사항에 대처를 빠르게 할 수 있는 코드를 만드는 작업이었습니다.
          
          새로 추가하고 싶은 기능이 모니터 간에 동기를 맞추어 동일한 영상을 표출하는 것인데, 기존에 만들어진 코드의 구조적인 한계로 부득이하게 리팩토링을 진행하게 되었습니다.
          기존에는 영상을 받아서 프로그램의 통제 없이 영상을 바로 표출하여 여러 개의 그래픽카드를 사용하는 경우 서로간의 동기가 맞지 않아 배젤이 없는 LED에서 눈에 띄게 티어링 현상이 생겼습니다. 이를 극복하기 위해 영상을 그래픽 카드에 내보내는 시점까지 프로그램이 통제하게 하여 동시에 표출이 가능하게 만드는 작업을 메인으로 진행했습니다. 
          
          그 외에도 기존 프로그램이 10년동안 유지되다 보니, 기능적으로 버리기도 하고 다시 구현해야 할 것이 많아서 설계나 리팩토링을 할 기회가 많았습니다.
          
      - layout: left
        title: 삼성 SDI 불량 배터리 검출 프로그램
        caption: 2021.9 - 2021.12
        quote: >
          AI 객체인식을 이용하여 불량 배터리를 검출하고 움직이는 사물의 qr코드를 인식하는 프로그램 개발
        description: | 
          그때는 아직 신사업팀의 정확한 제품 컨셉이 정해지지 않아 수요가 있는데로 간단하게 AI를 사용한 프로그램을 만들어서 데모를 보여주고 프로젝트를 진행하는 상황이었습니다. 이런 저런 수요들이 생기고 프로그램을 빠르고 직관적으로 개발해야 할일이 많이 생겼습니다.
          그러다보니 신사업팀의 개발 수요가 많이 생겨 기존에 제가 신사업팀에서 일해본 경험이 있기 때문에 지원요청을 받고 다시 팀을 옮겼습니다. 
          
          신사업팀으로 돌아와서 처음 개발하게 된 것은 삼성 SDI에서 움직이는 로봇에 실려있는 배터리를 촬영해서 불량을 검토하고 QR코드를 인식하여 엔지니어에게 전달해주는 프로그램이었습니다.
          삼성 SDS에서 사업 제안을 위해 데모영상을 부탁했고, 저는 폐 건전지로 상황을 모사해 직접 학습을 시키고 간단한 인퍼런스 프로그램을 제작하여 데모 영상을 전달했습니다. 
          
      - layout: left
        title: 옥외 주차 관제 시스템
        caption: 2022.1 - 2022.5
        quote: >
          AI 객체인식을 이용하여 불량 배터리를 검출하고 움직이는 사물의 qr코드를 인식하는 프로그램 개발
        description: | 
          그때는 아직 신사업팀의 정확한 제품 컨셉이 정해지지 않아 수요가 있는데로 간단하게 AI를 사용한 프로그램을 만들어서 데모를 보여주고 프로젝트를 진행하는 상황이었습니다. 이런 저런 수요들이 생기고 프로그램을 빠르고 직관적으로 개발해야 할일이 많이 생겼습니다.
          그러다보니 신사업팀의 개발 수요가 많이 생겨 기존에 제가 신사업팀에서 일해본 경험이 있기 때문에 지원요청을 받고 다시 팀을 옮겼습니다. 
          
          신사업팀으로 돌아와서 처음 개발하게 된 것은 삼성 SDI에서 움직이는 로봇에 실려있는 배터리를 촬영해서 불량을 검토하고 QR코드를 인식하여 엔지니어에게 전달해주는 프로그램이었습니다.
          삼성 SDS에서 사업 제안을 위해 데모영상을 부탁했고, 저는 폐 건전지로 상황을 모사해 직접 학습을 시키고 간단한 인퍼런스 프로그램을 제작하여 데모 영상을 전달했습니다. 
        
      - layout: left
        title: 고속도로 돌방정지 및 교통상황 시각화
        caption: 2022.6 - 2022.8
        quote: >
          객체인식으로 고속도로에서 사고로 정지되어 있는 차량 감지와, 현재 교통량을 파악하여 도로에 색상을 표시하는 시각화 프로그램 개발
        description: | 
          to do
          
      - layout: left
        title: 부설 주차 시스템
        caption: 2022.9 - 2022.11
        quote: >
          건물이나, 노외에 있는 주차장인데, 기존의 옥외주차 시스템에서 차번호 인식을 추가하여 어떤 차량이 어느 주차 슬롯에 주차했는지 판단하는 프로그램 개발
        description: | 
          to do
      
      - layout: left
        title: 실내 주차 시스템
        caption: 2022.12 - 2023.2
        quote: >
          마트나 백화점, 아파트 같은 실내 주차장에서 만공차를 판단하고, 실내 네비게이션을 제공하고, 사용자의 차량 주차위치를 제공해주는 프로그램 개발
        description: | 
          to do
       
      - layout: left
        title: 주차 통합 시스템
        caption: 2023.3 - 진행
        quote: >
          옥외주차, 부설주차, 실내주차를 통합하여 하나의 프로그램으로 개발
        description: | 
          to do
          
                    
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nuricon
        link: nuricon.co.kr
        # link_text: http://www.nuricon.co.kr/
        sub_title: Developer
        caption: November 2020 - Present
        quote: >
          뛰어난 기술력을 바탕으로 IP Wall Controller 시장의 점유율 1위를 고수하며, AI Vision 분야의 혁신적인 주차 시스템을 제공
        description: | # this will include new lines to allow paragraphs
            IP Wall은 모든 매체의 영상을 별도의 장비 없이 Network나, 영상케이블로 입력받아 다양한 형태의 Display에 실시간으로 표출 가능합니다.
            
            Smart Parking은 AI 기술을 이용해 주차장에 설치된 CCTV 영상을 분석하여 운전자에게 실시간으로 정보를 제공함으로써 주차장 이용 가능 여부 및 정확한 주차 위치정보를 제공하는 시스템입니다.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sejong University Graduate School
        caption: 2015 - 2019
        sub_title: Computer Engineering
        quote: >
          다양한 연구 경험 및 리더십 향상
        description: | 
          대학원에서는 주로 ADD와 사이버전에 관한 기초 연구를 진행했습니다. 이외에도 하둡 에코시스템을 사용하여 보안로그를 수집 및 분석, 데이터 마이닝을 통한 사용자 행위 패턴 추출 및 예측, 로그 분석을 이용한 공격 탐지 어플리케이션 개발 등 다양한 방면으로 연구를 진행했습니다.
          
          특허로는 라이브 포렌식 기반 공격 탐지 장치 및 방법, 로그 분석을 이용한 공격 탐지 장치 및 방법 두 개를 가지고 있고, 로그 분석을 이용한 공격 탐지 장치 및 방법은 기술이전을 진행하였습니다.
          
          랩실의 장을 맡아서 전반적인 업무를 분석하고 구성원 개개인이 어떤 일을 잘하는지 파악하여 적재적소에 배치하는 역할을 하였습니다. 그러면서 자연스럽게 팀원간의 조율할 수 있는 능력과 이끌수 있는 리더십을 터득했습니다.

  - title: Patent
    layout: text
    content: | # this will include new lines to allow paragraphs
      로그 분석을 이용한 공격 탐지 장치 및 방법
      - 등록번호: 1020226260000
      - 등록일자: 2019.09.10
      - 기술이전 진행

      라이브 포렌식 기반 공격 탐지 장치 및 방법
      - 등록번호: 1019976950000
      - 등록일자: 2019.07.02

  - title: Paper
    layout: text
    content: | # this will include new lines to allow paragraphs
      journal
      - (2019). Attack detection application with attack tree for mobile system using log analysis. Mobile Networks and Applications, 24, 184-192.
      - (2019). Fast attack detection system using log analysis and attack tree generation. Cluster Computing, 22, 1827-1835.
      - (2019). Design and implementation of simulation tool for cyber battle damage assessment using MOCE (measure of cyber effectiveness). Journal of the Korea Institute of Information Security & Cryptology, 29(2), 465-472.
      
      International Conference
      - (2017). Attack Tree Generation and Real-Time Attack Detection System Using Log Analysis. In Proceedings of the Korea Information Processing Society Conference (pp. 207-210). Korea Information Processing Society.
      - (2017). Cyber Battle damage assessment framework. In Proceedings of the Korea Information Processing Society Conference (pp. 178-181). Korea Information Processing Society.
      - (2019). Cyber battle damage assessment framework and detection of unauthorized wireless access point using machine learning. In Frontier Computing: Theory, Technologies and Applications (FC 2018) 7 (pp. 510-519). Springer Singapore.
      - (2019). A Method of Finger Counting by Fingertips Recognition. The International Conference on Big data, IoT, and Cloud Computing (BIC-19)
      - (2019). Development of Real-time Human Depression Diagnosis System by Analyzing Brainwaves. The International Conference on Big data, IoT, and Cloud Computing (BIC-19)
      - (2019). Unauthorized AP Detection System Based on Machine Learning. The International Conference on Big data, IoT, and Cloud Computing (BIC-19)
      
      국내 컨퍼런스
      - (2015). 그래프 마이닝을 이용한 사용자 행위 패턴 추출 및 예측. 한국통신학회 학술대회논문집, 86-87.
      - (2015). 네트워크중심 작전환경 구성을 위한 행위 패턴 예측. 한국인터넷정보학회 학술발표대회 논문집, 23-24.
      - (2015). 그래프 마이닝을 이용한 사용자의 행동 패턴 예측 및 상황인식. 한국정보과학회 학술발표논문집, 409-411.
      - (2015). 하둡 에코 시스템을 이용한 보안 로그 수집 및 분석. 한국정보처리학회 학술대회논문집, 22(2), 194-196.
      - (2016). 빅 데이터 시스템을 이용한 보안 로그 수집 및 분석 시스템 설계. 한국정보처리학회 학술대회논문집, 23(1), 321-323.
      - (2016). 빅 데이터 로그 관리 분석 시스템을 이용한 공격탐지 시스템. 한국통신학회 학술대회논문집, 121-122.
      - (2016). 사용자 행위 인지 및 예측을 위한 모델링과 라이프로그 빅데이터 시스템. 한국통신학회 학술대회논문집, 231-232.
      - (2016). 공격 트리 시나리오의 생성 및 분석을 이용한 침입 경로 예측 시스템. 한국인터넷정보학회 학술발표대회 논문집, 17(2), 13-14.
      - (2017). 로그 분석을 이용한 공격 트리 생성과 실시간공격 탐지 시스템. 한국정보처리학회 학술대회논문집, 24(1), 207-210.
      - (2017). 사이버 전투 피해 평가 프레임워크. 한국정보처리학회 학술대회논문집, 24(2), 178-181.
      - (2018). 사이버 전투 피해 평가 구조도 및 기계학습을 이용한 비인가 무선 AP 탐지 실험. 한국통신학회 학술대회논문집, 374-375.



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")
     
     

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
